# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nankana
tagline:          ''
description:      'Mobile first, elegant designs for the Sikh community.'
url:              http://nankana.vandchhako.com
baseurl:          /

author:
  name:           'Satnam Narang'
  url:            https://twitter.com/satnam

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/satnam/nankana
